package com.qsocialnow.common.model.cases;

public enum ActionParameter {

    COMMENT, RESOLUTION, TEXT, USER_RESOLVER, CATEGORIES_SET, CATEGORIES, USER, TEAM, FILES, SUBJECT, CATEGORIES_ADDED, CATEGORIES_REMOVED, USER_RESOLVERS, EXECUTOR,

}
